# Global parameter defaults
path: http
url: http://careers.nws.co.uk
user: admin
color: false

# Subcommand defaults (e.g. `wp config create`)
config create:
    dbhost: '127.0.0.1'
    dbname: 'wordpress-nws-2019'
    dbuser: 'root'
    dbpass: 'root'
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_MEMORY_LIMIT', '256M' );

core install:
    title: Careers | Net World Sports
    admin_user: admin
    admin_password: password
    admin_email: admin@example.com
